name: Build tree-sitter-javascript DLL

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          choco install cmake ninja llvm --force
          choco install visualstudio2022buildtools --force
          choco install visualstudio2022-workload-vctools --force
          RefreshEnv

      - name: Setup MSVC Compiler
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64

      - name: Clone tree-sitter core
        run: |
          git clone --depth 1 https://github.com/tree-sitter/tree-sitter.git ../tree-sitter

      - name: Build DLL
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja"
          ninja

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-javascript-dll
          path: build/tree-sitter-javascript.dll
